-- CAFS Data Export - 2026-03-25T09:21:12.392Z
SET FOREIGN_KEY_CHECKS = 0;

-- Data for users (3 rows)
TRUNCATE TABLE users;
INSERT INTO `users` (`id`, `username`, `password_hash`, `full_name`, `role`, `branch_id`, `status`, `created_at`) VALUES (1, 'cafscochin', '$2b$10$NXch4TOJl4WNLzHxZDhPW.va93FeN.tuQ4ciH2I7fep6NoRVI9oj.', 'Super Admin', 'SUPER_ADMIN', NULL, 'ACTIVE', '2026-03-22 18:56:21');
INSERT INTO `users` (`id`, `username`, `password_hash`, `full_name`, `role`, `branch_id`, `status`, `created_at`) VALUES (2, 'cafscochin1', '$2b$10$TkIojf5B3Jat9pjCel9iMuA3Pa0uiFqhHKDYF6apN/6Tw8aquMp/S', 'Cafs Cochin', 'ADMIN', 1, 'ACTIVE', '2026-03-24 06:06:40');
INSERT INTO `users` (`id`, `username`, `password_hash`, `full_name`, `role`, `branch_id`, `status`, `created_at`) VALUES (3, 'testmanager', '$2b$10$pRG0woUYFfBJ7RWO7hkt7e1k8tvLGDKpIS9GzPJPCFPY1deLIYbZa', 'Test Manager', 'MANAGER', 1, 'ACTIVE', '2026-03-24 11:39:30');

-- Data for branches (1 rows)
TRUNCATE TABLE branches;
INSERT INTO `branches` (`id`, `name`, `code`, `address`, `status`, `created_at`) VALUES (1, 'COCHIN', 'COK15003', 'NEAR COCHIN INTERNATIONAL AIRPORT, NEDUMBASSERY', NULL, '2026-03-24 06:05:29');

-- Data for consignments (13 rows)
TRUNCATE TABLE consignments;
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (1, 'SPICEJET LTD', 'SG', 'SG', 'AIRLINE', NULL, NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (2, 'AIR INDIA', 'AI', 'AI', 'AIRLINE', NULL, NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (3, 'INDIGO', '6E', '6E', 'AIRLINE', NULL, NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (4, 'VISTARA', 'UK', 'UK', 'AIRLINE', NULL, NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (5, 'GO FIRST', 'G8', 'G8', 'AIRLINE', NULL, NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (6, 'AIR ASIA', 'I5', 'I5', 'AIRLINE', NULL, NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (7, 'ERNAKULAM', 'EKM', NULL, 'LOCATION', 'Ernakulam, Kerala', NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (8, 'CHENNAI', 'MAA', NULL, 'LOCATION', 'Chennai, Tamil Nadu', NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (9, 'MUMBAI', 'BOM', NULL, 'LOCATION', 'Mumbai, Maharashtra', NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (10, 'DELHI', 'DEL', NULL, 'LOCATION', 'New Delhi', NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (11, 'MAERSK LINE', NULL, NULL, 'SHIP', 'Copenhagen, Denmark', NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (12, 'MSC - Mediterranean Shipping', NULL, NULL, 'SHIP', 'Geneva, Switzerland', NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `consignments` (`id`, `name`, `code`, `airline_code`, `type`, `address`, `contact_person`, `phone`, `email`, `status`, `created_at`) VALUES (13, 'Road Transport', NULL, NULL, 'ROAD', NULL, NULL, NULL, NULL, 'ACTIVE', '2026-03-22 18:50:54');

-- Data for items (22 rows)
TRUNCATE TABLE items;
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (1, 'J W BLACK LABEL 5 CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (2, 'BEER-BUDWEISER CANS 35.5 CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (3, 'VODKA STOLI PREMIUM MINI 5CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (4, 'GLENMORAY 12YO 5 CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (5, 'ALBERT BICHOT MOULINS', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (6, '2019 CHATEAU TEYSSIER 75CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (7, 'RAMPUR DOUBLE CASK 750ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (8, 'MONKEY SHOULDER 50ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (9, 'JACK DANIELS WHISKY 100CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (10, 'ROKU GIN 70CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (11, '1000 RESERVA ANEJO 50ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (12, 'BAILEYS IRISH CREAM LIQUEUR 100CL', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (13, 'BACARDI RONCARTA BLANCA 1000ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (14, 'VODKA GREY GOOSE 1000ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (15, 'ABSOLUT ORIGINAL VODKA 1000ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (16, 'DEWARS WHITE LABEL WHISKY 1000ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (17, 'GLENLIVET SINGLE MALT WHISKY 1000ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (18, 'MADEIRA ABERFELDY 16 WHISKY', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (19, 'SAINT CLAIR GRIMM 750ML', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (20, '2021 CHATEAU DU MONTHLY RLV', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (21, 'HENLEY CAMP GRANSER 8.7 CL 40W', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');
INSERT INTO `items` (`id`, `description`, `unit`, `hsn_code`, `category`, `min_stock`, `current_stock`, `status`, `created_at`) VALUES (22, 'HENLEY STAMP GHASAR CIL 18 CLOW', 'PCS', NULL, NULL, 0, 0, 'ACTIVE', '2026-03-22 18:50:54');

-- Data for inward_entries (4 rows)
TRUNCATE TABLE inward_entries;
INSERT INTO `inward_entries` (`id`, `be_no`, `be_date`, `bond_no`, `bond_date`, `shipping_bill_no`, `shipping_bill_date`, `flight_no`, `awb_no`, `bill_no`, `received_by`, `otl_no`, `mode_of_receipt`, `qty_advised`, `qty_received`, `breakage_shortage`, `date_of_receipt`, `consignment_id`, `item_id`, `initial_bonding_date`, `initial_bonding_expiry`, `extended_bonding_date1`, `extended_bonding_expiry1`, `extended_bonding_date2`, `extended_bonding_expiry2`, `extended_bonding_date3`, `extended_bonding_expiry3`, `bank_guarantee`, `relinquishment`, `duty_rate`, `value_rate`, `value`, `duty`, `sl_no_import_invoice`, `pkg_marks`, `pkg_description`, `transport_reg_no`, `date_of_order_section_60`, `warehouse_code`, `warehouse_address`, `customs_station`, `remarks`, `branch_id`, `created_at`) VALUES (5, 'BEOROORO', '2026-03-13 18:30:00', 'NEW BOND LIST', '2026-03-15 18:30:00', 'NEW', NULL, 'AA2333', NULL, NULL, NULL, NULL, 'AIRLINE', 50, 50, 0, '2026-03-12 18:30:00', 6, NULL, '2026-03-22 18:30:00', '2027-03-15 18:30:00', NULL, '2026-03-30 18:30:00', NULL, '2028-02-29 18:30:00', NULL, '2026-03-30 18:30:00', 'NEW', 0, '15.0000', '123334.0000', '2000.00', '200.00', 'NEW', NULL, NULL, NULL, '2026-03-07 18:30:00', 'Cok15003', 'Nayathode P.O Angamali Kerala 683572', 'COK', NULL, 1, '2026-03-22 19:25:37');
INSERT INTO `inward_entries` (`id`, `be_no`, `be_date`, `bond_no`, `bond_date`, `shipping_bill_no`, `shipping_bill_date`, `flight_no`, `awb_no`, `bill_no`, `received_by`, `otl_no`, `mode_of_receipt`, `qty_advised`, `qty_received`, `breakage_shortage`, `date_of_receipt`, `consignment_id`, `item_id`, `initial_bonding_date`, `initial_bonding_expiry`, `extended_bonding_date1`, `extended_bonding_expiry1`, `extended_bonding_date2`, `extended_bonding_expiry2`, `extended_bonding_date3`, `extended_bonding_expiry3`, `bank_guarantee`, `relinquishment`, `duty_rate`, `value_rate`, `value`, `duty`, `sl_no_import_invoice`, `pkg_marks`, `pkg_description`, `transport_reg_no`, `date_of_order_section_60`, `warehouse_code`, `warehouse_address`, `customs_station`, `remarks`, `branch_id`, `created_at`) VALUES (6, 'BE/2024/001', '2026-03-25 18:30:00', '10128888', '2026-03-24 18:30:00', '33WRWRU', NULL, 'A1 902', NULL, NULL, NULL, NULL, 'AIRLINE', 150, 150, 0, '2026-03-24 18:30:00', 2, NULL, '2026-03-11 18:30:00', '2026-04-28 18:30:00', NULL, NULL, NULL, NULL, NULL, NULL, 'NA', 0, '15.0000', NULL, '3750.00', '1250.00', 'REWRR', NULL, NULL, NULL, '2026-03-17 18:30:00', 'COK15003', 'Nayathode P.O Angamali Kerala 683572', 'COK', NULL, 1, '2026-03-25 08:05:34');
INSERT INTO `inward_entries` (`id`, `be_no`, `be_date`, `bond_no`, `bond_date`, `shipping_bill_no`, `shipping_bill_date`, `flight_no`, `awb_no`, `bill_no`, `received_by`, `otl_no`, `mode_of_receipt`, `qty_advised`, `qty_received`, `breakage_shortage`, `date_of_receipt`, `consignment_id`, `item_id`, `initial_bonding_date`, `initial_bonding_expiry`, `extended_bonding_date1`, `extended_bonding_expiry1`, `extended_bonding_date2`, `extended_bonding_expiry2`, `extended_bonding_date3`, `extended_bonding_expiry3`, `bank_guarantee`, `relinquishment`, `duty_rate`, `value_rate`, `value`, `duty`, `sl_no_import_invoice`, `pkg_marks`, `pkg_description`, `transport_reg_no`, `date_of_order_section_60`, `warehouse_code`, `warehouse_address`, `customs_station`, `remarks`, `branch_id`, `created_at`) VALUES (7, 'BEOROORO', '2026-03-24 18:30:00', 'NEW BOND LIST', '2026-03-24 18:30:00', '33WRWRU', NULL, 'A1 902', NULL, NULL, NULL, NULL, 'AIRLINE', 150, 150, 0, '2026-03-24 18:30:00', 2, NULL, '2026-03-24 18:30:00', '2028-03-29 18:30:00', NULL, NULL, NULL, NULL, NULL, NULL, 'NA', 0, '15.0000', NULL, '4500.00', '1230.00', 'REWRR', NULL, NULL, NULL, '2026-03-17 18:30:00', 'COK15003', 'Nayathode P.O Angamali Kerala 683572', 'COK', NULL, 1, '2026-03-25 08:07:43');
INSERT INTO `inward_entries` (`id`, `be_no`, `be_date`, `bond_no`, `bond_date`, `shipping_bill_no`, `shipping_bill_date`, `flight_no`, `awb_no`, `bill_no`, `received_by`, `otl_no`, `mode_of_receipt`, `qty_advised`, `qty_received`, `breakage_shortage`, `date_of_receipt`, `consignment_id`, `item_id`, `initial_bonding_date`, `initial_bonding_expiry`, `extended_bonding_date1`, `extended_bonding_expiry1`, `extended_bonding_date2`, `extended_bonding_expiry2`, `extended_bonding_date3`, `extended_bonding_expiry3`, `bank_guarantee`, `relinquishment`, `duty_rate`, `value_rate`, `value`, `duty`, `sl_no_import_invoice`, `pkg_marks`, `pkg_description`, `transport_reg_no`, `date_of_order_section_60`, `warehouse_code`, `warehouse_address`, `customs_station`, `remarks`, `branch_id`, `created_at`) VALUES (8, 'TestBE-999', '2026-03-23 18:30:00', 'TestBond-999', '2026-03-08 18:30:00', NULL, NULL, 'AA2333', NULL, NULL, NULL, NULL, 'AIRLINE', 100, 100, 0, '2026-03-23 18:30:00', 6, NULL, '2026-03-24 18:30:00', '2026-04-21 18:30:00', NULL, '2026-06-17 18:30:00', NULL, '2026-04-29 18:30:00', NULL, NULL, 'NEW', 0, '15.0000', NULL, '4500.00', '1400.00', NULL, NULL, NULL, NULL, NULL, 'COK15003', 'Nayathode P.O Angamali Kerala 683572', 'COK', NULL, 1, '2026-03-25 08:26:30');

-- Data for inward_items (4 rows)
TRUNCATE TABLE inward_items;
INSERT INTO `inward_items` (`id`, `inward_id`, `item_id`, `description`, `qty`, `unit`, `value`, `duty`, `qty_out`, `bond_no`, `bond_expiry`, `unit_value`, `value_amount`, `unit_duty`, `duty_amount`, `hsn_code`, `shelf_life_date`, `duty_percent`) VALUES (1, 5, NULL, 'BACARDI RONCARTA BLANCA 1000ML', 50, 'PCS', '2000.00', '200.00', 0, NULL, NULL, NULL, NULL, NULL, NULL, '10', '2026-03-13 18:30:00', '15+15+15');
INSERT INTO `inward_items` (`id`, `inward_id`, `item_id`, `description`, `qty`, `unit`, `value`, `duty`, `qty_out`, `bond_no`, `bond_expiry`, `unit_value`, `value_amount`, `unit_duty`, `duty_amount`, `hsn_code`, `shelf_life_date`, `duty_percent`) VALUES (2, 6, NULL, 'BACARDI RONCARTA BLANCA 1000ML', 150, 'PCS', '3750.00', '1250.00', 0, NULL, NULL, NULL, NULL, NULL, NULL, '133₹', '2027-05-04 18:30:00', '15+15+15');
INSERT INTO `inward_items` (`id`, `inward_id`, `item_id`, `description`, `qty`, `unit`, `value`, `duty`, `qty_out`, `bond_no`, `bond_expiry`, `unit_value`, `value_amount`, `unit_duty`, `duty_amount`, `hsn_code`, `shelf_life_date`, `duty_percent`) VALUES (3, 7, NULL, 'BEER-BUDWEISER CANS 35.5 CL', 150, 'PCS', '4500.00', '1230.00', 0, NULL, NULL, NULL, NULL, NULL, NULL, '2200', NULL, '10');
INSERT INTO `inward_items` (`id`, `inward_id`, `item_id`, `description`, `qty`, `unit`, `value`, `duty`, `qty_out`, `bond_no`, `bond_expiry`, `unit_value`, `value_amount`, `unit_duty`, `duty_amount`, `hsn_code`, `shelf_life_date`, `duty_percent`) VALUES (4, 8, NULL, 'BAILEYS IRISH CREAM LIQUEUR 100CL', 100, 'PCS', '4500.00', '1400.00', 0, NULL, NULL, NULL, NULL, NULL, NULL, '1333', '2027-03-23 18:30:00', '15+15');

-- Data for shipping_bills (1 rows)
TRUNCATE TABLE shipping_bills;
INSERT INTO `shipping_bills` (`id`, `sb_no`, `consignment_id`, `entered_date`, `status`, `approved_by`, `approved_at`, `remarks`, `created_at`, `shipping_bill_no`, `shipping_bill_date`, `flight_no`, `etd`, `vt`, `port_of_discharge`, `country_of_destination`, `station`, `exporter_name`, `exporter_address`, `entered_no`, `branch_id`) VALUES (1, '', 6, NULL, 'APPROVED', 'Test Manager', '2026-03-25 06:37:20', NULL, '2026-03-22 19:58:28', '1334444', '2026-03-22 18:30:00', 'New', '1899-11-29 18:38:50', 'new', 'COK/KWI/COK', 'KWI', 'COCHIN', 'CASINO AIR CATERERS & FLIGHT SERVICES', '(Unit of Anjali Hotels Pvt.Ltd)', 'New', 1);

-- Data for outward_entries (1 rows)
TRUNCATE TABLE outward_entries;
INSERT INTO `outward_entries` (`id`, `dispatch_date`, `consignment_id`, `inward_id`, `nature_of_removal`, `shipping_bill_no`, `shipping_bill_date`, `flight_no`, `purpose`, `gate_pass_no`, `released_by`, `total_dispatched`, `total_returned`, `value`, `duty`, `registration_no_of_means_of_transport`, `otl_no`, `remarks`, `branch_id`, `created_at`, `shipping_bill_id`) VALUES (1, '2026-03-22 18:30:00', 6, 5, 'Re-export', '1334444', '2026-03-22 18:30:00', 'New', 'Re-export', NULL, NULL, 50, 0, '2000.00', '750.00', 'new', NULL, 'Dispatched from Shipping Bill #1334444', 1, '2026-03-25 06:37:20', 1);

-- Data for outward_items (1 rows)
TRUNCATE TABLE outward_items;
INSERT INTO `outward_items` (`id`, `outward_id`, `inward_item_id`, `inward_id`, `item_id`, `description`, `qty_dispatched`, `qty_returned_bag`, `value`, `duty`) VALUES (1, 1, 1, 5, NULL, 'BACARDI RONCARTA BLANCA 1000ML', 50, 0, '40.00', '15.00');

-- Data for flight_numbers (2 rows)
TRUNCATE TABLE flight_numbers;
INSERT INTO `flight_numbers` (`id`, `consignment_id`, `flight_no`, `status`, `created_at`) VALUES (1, 2, 'A1 902', 'ACTIVE', '2026-03-22 10:09:58');
INSERT INTO `flight_numbers` (`id`, `consignment_id`, `flight_no`, `status`, `created_at`) VALUES (2, 6, 'AA2333', 'ACTIVE', '2026-03-22 19:41:18');

SET FOREIGN_KEY_CHECKS = 1;
