SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `branches` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `code` varchar(50) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `consignments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `code` varchar(50) DEFAULT NULL,
  `airline_code` varchar(10) DEFAULT NULL,
  `type` enum('AIRLINE','LOCATION','SHIP','ROAD','OTHER') DEFAULT 'OTHER',
  `address` text DEFAULT NULL,
  `contact_person` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `damaged_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `reported_date` date NOT NULL,
  `inward_item_id` int(11) NOT NULL,
  `qty_damaged` int(11) NOT NULL,
  `reason` text DEFAULT NULL,
  `reported_by` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `branch_id` int(11) DEFAULT NULL,
  `inward_id` int(11) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `inward_item_id` (`inward_item_id`),
  CONSTRAINT `damaged_items_ibfk_1` FOREIGN KEY (`inward_item_id`) REFERENCES `inward_items` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `flight_numbers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `consignment_id` int(11) NOT NULL,
  `flight_no` varchar(20) NOT NULL,
  `status` enum('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `consignment_id` (`consignment_id`),
  CONSTRAINT `flight_numbers_ibfk_1` FOREIGN KEY (`consignment_id`) REFERENCES `consignments` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `inward_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `be_no` varchar(50) DEFAULT NULL,
  `be_date` date DEFAULT NULL,
  `bond_no` varchar(50) DEFAULT NULL,
  `bond_date` date DEFAULT NULL,
  `shipping_bill_no` varchar(50) DEFAULT NULL,
  `shipping_bill_date` date DEFAULT NULL,
  `flight_no` varchar(50) DEFAULT NULL,
  `awb_no` varchar(50) DEFAULT NULL,
  `bill_no` varchar(50) DEFAULT NULL,
  `received_by` varchar(100) DEFAULT NULL,
  `otl_no` varchar(50) DEFAULT NULL,
  `mode_of_receipt` varchar(50) DEFAULT 'By Road',
  `qty_advised` int(11) DEFAULT NULL,
  `qty_received` int(11) NOT NULL DEFAULT 0,
  `breakage_shortage` int(11) DEFAULT 0,
  `date_of_receipt` date NOT NULL,
  `consignment_id` int(11) DEFAULT NULL,
  `item_id` int(11) DEFAULT NULL,
  `initial_bonding_date` date DEFAULT NULL,
  `initial_bonding_expiry` date DEFAULT NULL,
  `extended_bonding_date1` date DEFAULT NULL,
  `extended_bonding_expiry1` date DEFAULT NULL,
  `extended_bonding_date2` date DEFAULT NULL,
  `extended_bonding_expiry2` date DEFAULT NULL,
  `extended_bonding_date3` date DEFAULT NULL,
  `extended_bonding_expiry3` date DEFAULT NULL,
  `bank_guarantee` text DEFAULT NULL,
  `relinquishment` tinyint(1) DEFAULT 0,
  `duty_rate` decimal(15,4) DEFAULT NULL,
  `value_rate` decimal(15,4) DEFAULT NULL,
  `value` decimal(15,2) DEFAULT NULL,
  `duty` decimal(15,2) DEFAULT NULL,
  `sl_no_import_invoice` varchar(50) DEFAULT NULL,
  `pkg_marks` text DEFAULT NULL,
  `pkg_description` text DEFAULT NULL,
  `transport_reg_no` varchar(50) DEFAULT NULL,
  `date_of_order_section_60` date DEFAULT NULL,
  `warehouse_code` varchar(50) DEFAULT NULL,
  `warehouse_address` text DEFAULT NULL,
  `customs_station` varchar(100) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `branch_id` (`branch_id`),
  KEY `consignment_id` (`consignment_id`),
  KEY `item_id` (`item_id`),
  CONSTRAINT `inward_entries_ibfk_1` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `inward_entries_ibfk_2` FOREIGN KEY (`consignment_id`) REFERENCES `consignments` (`id`),
  CONSTRAINT `inward_entries_ibfk_3` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `inward_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `inward_id` int(11) NOT NULL,
  `item_id` int(11) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `qty` int(11) NOT NULL,
  `unit` varchar(20) DEFAULT NULL,
  `value` decimal(15,2) DEFAULT NULL,
  `duty` decimal(15,2) DEFAULT NULL,
  `qty_out` int(11) DEFAULT 0,
  `bond_no` varchar(50) DEFAULT NULL,
  `bond_expiry` date DEFAULT NULL,
  `unit_value` decimal(15,4) DEFAULT NULL,
  `value_amount` decimal(15,2) DEFAULT NULL,
  `unit_duty` decimal(15,4) DEFAULT NULL,
  `duty_amount` decimal(15,2) DEFAULT NULL,
  `hsn_code` varchar(50) DEFAULT NULL,
  `shelf_life_date` date DEFAULT NULL,
  `duty_percent` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `inward_id` (`inward_id`),
  KEY `item_id` (`item_id`),
  CONSTRAINT `inward_items_ibfk_1` FOREIGN KEY (`inward_id`) REFERENCES `inward_entries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `inward_items_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) NOT NULL,
  `unit` varchar(20) DEFAULT 'PCS',
  `hsn_code` varchar(50) DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `min_stock` int(11) DEFAULT 0,
  `current_stock` int(11) DEFAULT 0,
  `status` enum('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `outward_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dispatch_date` date NOT NULL,
  `consignment_id` int(11) DEFAULT NULL,
  `inward_id` int(11) DEFAULT NULL,
  `nature_of_removal` varchar(100) DEFAULT NULL,
  `shipping_bill_no` varchar(50) DEFAULT NULL,
  `shipping_bill_date` date DEFAULT NULL,
  `flight_no` varchar(50) DEFAULT NULL,
  `purpose` varchar(100) DEFAULT NULL,
  `gate_pass_no` varchar(50) DEFAULT NULL,
  `released_by` varchar(100) DEFAULT NULL,
  `total_dispatched` int(11) DEFAULT 0,
  `total_returned` int(11) DEFAULT 0,
  `value` decimal(15,2) DEFAULT NULL,
  `duty` decimal(15,2) DEFAULT NULL,
  `registration_no_of_means_of_transport` varchar(50) DEFAULT NULL,
  `otl_no` varchar(50) DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `shipping_bill_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `branch_id` (`branch_id`),
  KEY `consignment_id` (`consignment_id`),
  KEY `inward_id` (`inward_id`),
  CONSTRAINT `outward_entries_ibfk_1` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`),
  CONSTRAINT `outward_entries_ibfk_2` FOREIGN KEY (`consignment_id`) REFERENCES `consignments` (`id`),
  CONSTRAINT `outward_entries_ibfk_3` FOREIGN KEY (`inward_id`) REFERENCES `inward_entries` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `outward_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `outward_id` int(11) NOT NULL,
  `inward_item_id` int(11) NOT NULL,
  `inward_id` int(11) DEFAULT NULL,
  `item_id` int(11) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `qty_dispatched` int(11) NOT NULL,
  `qty_returned_bag` int(11) DEFAULT 0,
  `value` decimal(15,2) DEFAULT NULL,
  `duty` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `outward_id` (`outward_id`),
  KEY `inward_item_id` (`inward_item_id`),
  KEY `inward_id` (`inward_id`),
  KEY `item_id` (`item_id`),
  CONSTRAINT `outward_items_ibfk_1` FOREIGN KEY (`outward_id`) REFERENCES `outward_entries` (`id`) ON DELETE CASCADE,
  CONSTRAINT `outward_items_ibfk_2` FOREIGN KEY (`inward_item_id`) REFERENCES `inward_items` (`id`),
  CONSTRAINT `outward_items_ibfk_3` FOREIGN KEY (`inward_id`) REFERENCES `inward_entries` (`id`),
  CONSTRAINT `outward_items_ibfk_4` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `return_stock_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `return_date` date NOT NULL,
  `inward_id` int(11) DEFAULT NULL,
  `inward_item_id` int(11) DEFAULT NULL,
  `qty_returned` int(11) NOT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `authorised_by` varchar(100) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `branch_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `inward_id` (`inward_id`),
  KEY `inward_item_id` (`inward_item_id`),
  CONSTRAINT `return_stock_entries_ibfk_1` FOREIGN KEY (`inward_id`) REFERENCES `inward_entries` (`id`) ON DELETE SET NULL,
  CONSTRAINT `return_stock_entries_ibfk_2` FOREIGN KEY (`inward_item_id`) REFERENCES `inward_items` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `shipping_bill_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `shipping_bill_id` int(11) NOT NULL,
  `inward_item_id` int(11) NOT NULL,
  `inward_id` int(11) NOT NULL,
  `item_id` int(11) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `bond_no` varchar(50) DEFAULT NULL,
  `bond_expiry` date DEFAULT NULL,
  `qty` int(11) NOT NULL,
  `unit_value` decimal(15,4) DEFAULT NULL,
  `value_amount` decimal(15,2) DEFAULT NULL,
  `unit_duty` decimal(15,4) DEFAULT NULL,
  `duty_amount` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `shipping_bill_id` (`shipping_bill_id`),
  KEY `inward_item_id` (`inward_item_id`),
  KEY `inward_id` (`inward_id`),
  CONSTRAINT `shipping_bill_items_ibfk_1` FOREIGN KEY (`shipping_bill_id`) REFERENCES `shipping_bills` (`id`) ON DELETE CASCADE,
  CONSTRAINT `shipping_bill_items_ibfk_2` FOREIGN KEY (`inward_item_id`) REFERENCES `inward_items` (`id`),
  CONSTRAINT `shipping_bill_items_ibfk_3` FOREIGN KEY (`inward_id`) REFERENCES `inward_entries` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `shipping_bills` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sb_no` varchar(50) NOT NULL,
  `consignment_id` int(11) DEFAULT NULL,
  `entered_date` date DEFAULT NULL,
  `status` varchar(20) DEFAULT 'DRAFT',
  `approved_by` varchar(100) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `remarks` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `shipping_bill_no` varchar(50) DEFAULT NULL,
  `shipping_bill_date` date DEFAULT NULL,
  `flight_no` varchar(50) DEFAULT NULL,
  `etd` date DEFAULT NULL,
  `vt` varchar(50) DEFAULT NULL,
  `port_of_discharge` varchar(100) DEFAULT NULL,
  `country_of_destination` varchar(100) DEFAULT NULL,
  `station` varchar(100) DEFAULT NULL,
  `exporter_name` varchar(255) DEFAULT NULL,
  `exporter_address` text DEFAULT NULL,
  `entered_no` varchar(50) DEFAULT NULL,
  `branch_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sb_no` (`sb_no`),
  KEY `consignment_id` (`consignment_id`),
  CONSTRAINT `shipping_bills_ibfk_1` FOREIGN KEY (`consignment_id`) REFERENCES `consignments` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `role` enum('SUPER_ADMIN','ADMIN','MANAGER','APPROVER','STAFF') NOT NULL DEFAULT 'STAFF',
  `branch_id` int(11) DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE') DEFAULT 'ACTIVE',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `branch_id` (`branch_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`branch_id`) REFERENCES `branches` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SET FOREIGN_KEY_CHECKS = 1;
